export const localeCodes = ["en", "fr", "ru", "uk", "tr", "fa", "ar"];

export const messages = {
  en: {
    appName: "CROUS operations", signIn: "Sign in", username: "Telegram username", password: "Password", signInHelp: "Use your administrator account.", signOut: "Sign out", dashboard: "Dashboard", administrators: "Administrators", paidUsers: "Paid users", transactions: "Transactions", overview: "Overview", week: "Week", month: "Month", year: "Year", totalUsers: "Total users", paidSubscribers: "Active paid subscribers", monitoringAnchors: "Active monitoring anchors", revenue: "Revenue", recentBuyers: "Recent buyers", search: "Search", previous: "Previous", next: "Next", page: "Page", of: "of", results: "results", loading: "Loading data", empty: "No matching records", retry: "Try again", error: "We could not load this data.", addAdmin: "Add administrator", name: "Name", role: "Role", status: "Status", created: "Created", lastLogin: "Last login", active: "Active", inactive: "Inactive", superadmin: "Superadmin", admin: "Admin", createAdmin: "Create administrator", passwordHelp: "At least 12 characters with uppercase, lowercase, and a number.", showPassword: "Show password", hidePassword: "Hide password", cancel: "Cancel", save: "Save", close: "Close", viewDetails: "View details", plan: "Plan", starts: "Starts", ends: "Ends", lastPayment: "Last payment", activeSearches: "Active searches", transaction: "Transaction", amount: "Amount", mode: "Mode", live: "Live", test: "Test", purchased: "Purchased", identifier: "Identifier", language: "Language", searchArea: "Search area", keyboardHelp: "Keyboard help", keyboardBody: "Tab moves through controls. Enter or Space opens a selected row. Escape closes dialogs.", skip: "Skip to content", menu: "Menu", filters: "Filters", noData: "No data for this period", refresh: "Refresh", signedInAs: "Signed in as", invalidLogin: "Check your username and password.", required: "This field is required.", unknown: "Not available", monitoring: "Monitoring", current: "Current", sessionExpired: "Your session has expired. Sign in again."
  },
  fr: {
    appName: "Opérations CROUS", signIn: "Se connecter", username: "Nom d’utilisateur Telegram", password: "Mot de passe", signInHelp: "Utilisez votre compte administrateur.", signOut: "Se déconnecter", dashboard: "Tableau de bord", administrators: "Administrateurs", paidUsers: "Utilisateurs payants", transactions: "Transactions", overview: "Vue d’ensemble", week: "Semaine", month: "Mois", year: "Année", totalUsers: "Utilisateurs", paidSubscribers: "Abonnés payants actifs", monitoringAnchors: "Recherches actives", revenue: "Revenus", recentBuyers: "Achats récents", search: "Rechercher", previous: "Précédent", next: "Suivant", page: "Page", of: "sur", results: "résultats", loading: "Chargement", empty: "Aucun résultat", retry: "Réessayer", error: "Impossible de charger ces données.", addAdmin: "Ajouter un administrateur", name: "Nom", role: "Rôle", status: "Statut", created: "Créé", lastLogin: "Dernière connexion", active: "Actif", inactive: "Inactif", superadmin: "Superadministrateur", admin: "Administrateur", createAdmin: "Créer l’administrateur", passwordHelp: "Au moins 12 caractères avec une majuscule, une minuscule et un chiffre.", showPassword: "Afficher le mot de passe", hidePassword: "Masquer le mot de passe", cancel: "Annuler", save: "Enregistrer", close: "Fermer", viewDetails: "Voir les détails", plan: "Forfait", starts: "Début", ends: "Fin", lastPayment: "Dernier paiement", activeSearches: "Recherches actives", transaction: "Transaction", amount: "Montant", mode: "Mode", live: "Production", test: "Test", purchased: "Acheté", identifier: "Identifiant", language: "Langue", searchArea: "Zone de recherche", keyboardHelp: "Aide clavier", keyboardBody: "Tab passe d’un contrôle à l’autre. Entrée ou Espace ouvre une ligne. Échap ferme les fenêtres.", skip: "Aller au contenu", menu: "Menu", filters: "Filtres", noData: "Aucune donnée pour cette période", refresh: "Actualiser", signedInAs: "Connecté en tant que", invalidLogin: "Vérifiez votre nom d’utilisateur et votre mot de passe.", required: "Ce champ est obligatoire.", unknown: "Indisponible", monitoring: "Surveillance", current: "Actuel", sessionExpired: "Votre session a expiré. Connectez-vous à nouveau."
  },
  ru: { appName: "Операции CROUS", signIn: "Войти", username: "Имя пользователя Telegram", password: "Пароль", signOut: "Выйти", dashboard: "Панель", administrators: "Администраторы", paidUsers: "Платные пользователи", transactions: "Транзакции", overview: "Обзор", week: "Неделя", month: "Месяц", year: "Год", totalUsers: "Пользователи", paidSubscribers: "Активные платные подписки", monitoringAnchors: "Активные поиски", revenue: "Выручка", recentBuyers: "Последние покупки", search: "Поиск", previous: "Назад", next: "Далее", page: "Страница", of: "из", results: "результатов", loading: "Загрузка", empty: "Нет записей", retry: "Повторить", error: "Не удалось загрузить данные.", addAdmin: "Добавить администратора", name: "Имя", role: "Роль", status: "Статус", created: "Создан", lastLogin: "Последний вход", active: "Активен", inactive: "Неактивен", superadmin: "Суперадминистратор", admin: "Администратор", createAdmin: "Создать администратора", passwordHelp: "Не менее 12 символов, строчная, заглавная буква и цифра.", showPassword: "Показать пароль", hidePassword: "Скрыть пароль", cancel: "Отмена", save: "Сохранить", close: "Закрыть", viewDetails: "Открыть", plan: "План", starts: "Начало", ends: "Конец", lastPayment: "Последний платёж", activeSearches: "Активные поиски", transaction: "Транзакция", amount: "Сумма", mode: "Режим", live: "Рабочий", test: "Тест", purchased: "Покупка", identifier: "Идентификатор", language: "Язык", searchArea: "Район поиска", keyboardHelp: "Справка по клавиатуре", keyboardBody: "Tab перемещает фокус. Enter или Space открывают строку. Escape закрывает диалог.", skip: "К содержимому", menu: "Меню", filters: "Фильтры", noData: "Нет данных за период", refresh: "Обновить", signedInAs: "Вы вошли как", invalidLogin: "Проверьте имя пользователя и пароль.", required: "Заполните поле.", unknown: "Нет данных", monitoring: "Мониторинг", current: "Текущий", sessionExpired: "Сессия истекла. Войдите снова." },
  uk: { appName: "Операції CROUS", signIn: "Увійти", username: "Ім’я користувача Telegram", password: "Пароль", signOut: "Вийти", dashboard: "Панель", administrators: "Адміністратори", paidUsers: "Платні користувачі", transactions: "Транзакції", overview: "Огляд", week: "Тиждень", month: "Місяць", year: "Рік", totalUsers: "Користувачі", paidSubscribers: "Активні платні підписки", monitoringAnchors: "Активні пошуки", revenue: "Дохід", recentBuyers: "Останні покупки", search: "Пошук", previous: "Назад", next: "Далі", page: "Сторінка", of: "з", results: "результатів", loading: "Завантаження", empty: "Записів немає", retry: "Повторити", error: "Не вдалося завантажити дані.", addAdmin: "Додати адміністратора", name: "Ім’я", role: "Роль", status: "Статус", created: "Створено", lastLogin: "Останній вхід", active: "Активний", inactive: "Неактивний", superadmin: "Суперадміністратор", admin: "Адміністратор", createAdmin: "Створити адміністратора", passwordHelp: "Щонайменше 12 символів, велика, мала літера і цифра.", showPassword: "Показати пароль", hidePassword: "Приховати пароль", cancel: "Скасувати", save: "Зберегти", close: "Закрити", viewDetails: "Відкрити", plan: "План", starts: "Початок", ends: "Кінець", lastPayment: "Останній платіж", activeSearches: "Активні пошуки", transaction: "Транзакція", amount: "Сума", mode: "Режим", live: "Робочий", test: "Тест", purchased: "Куплено", identifier: "Ідентифікатор", language: "Мова", searchArea: "Район пошуку", keyboardHelp: "Довідка клавіатури", keyboardBody: "Tab переходить між елементами. Enter або Пробіл відкривають рядок. Escape закриває діалог.", skip: "До вмісту", menu: "Меню", filters: "Фільтри", noData: "Немає даних за цей період", refresh: "Оновити", signedInAs: "Ви увійшли як", invalidLogin: "Перевірте ім’я користувача і пароль.", required: "Заповніть поле.", unknown: "Немає даних", monitoring: "Моніторинг", current: "Поточний", sessionExpired: "Сесію завершено. Увійдіть знову." },
  tr: { appName: "CROUS işlemleri", signIn: "Giriş yap", username: "Telegram kullanıcı adı", password: "Parola", signOut: "Çıkış yap", dashboard: "Pano", administrators: "Yöneticiler", paidUsers: "Ücretli kullanıcılar", transactions: "İşlemler", overview: "Genel bakış", week: "Hafta", month: "Ay", year: "Yıl", totalUsers: "Kullanıcılar", paidSubscribers: "Etkin ücretli aboneler", monitoringAnchors: "Etkin aramalar", revenue: "Gelir", recentBuyers: "Son satın alanlar", search: "Ara", previous: "Önceki", next: "Sonraki", page: "Sayfa", of: "/", results: "sonuç", loading: "Yükleniyor", empty: "Kayıt bulunamadı", retry: "Tekrar dene", error: "Veriler yüklenemedi.", addAdmin: "Yönetici ekle", name: "Ad", role: "Rol", status: "Durum", created: "Oluşturuldu", lastLogin: "Son giriş", active: "Etkin", inactive: "Devre dışı", superadmin: "Süper yönetici", admin: "Yönetici", createAdmin: "Yönetici oluştur", passwordHelp: "En az 12 karakter, büyük harf, küçük harf ve sayı.", showPassword: "Parolayı göster", hidePassword: "Parolayı gizle", cancel: "İptal", save: "Kaydet", close: "Kapat", viewDetails: "Aç", plan: "Plan", starts: "Başlangıç", ends: "Bitiş", lastPayment: "Son ödeme", activeSearches: "Etkin aramalar", transaction: "İşlem", amount: "Tutar", mode: "Mod", live: "Canlı", test: "Test", purchased: "Satın alma", identifier: "Kimlik", language: "Dil", searchArea: "Arama alanı", keyboardHelp: "Klavye yardımı", keyboardBody: "Tab denetimler arasında geçer. Enter veya Boşluk satırı açar. Escape iletişim kutusunu kapatır.", skip: "İçeriğe geç", menu: "Menü", filters: "Filtreler", noData: "Bu dönem için veri yok", refresh: "Yenile", signedInAs: "Giriş yapan", invalidLogin: "Kullanıcı adınızı ve parolanızı kontrol edin.", required: "Bu alan zorunludur.", unknown: "Kullanılamıyor", monitoring: "İzleme", current: "Geçerli", sessionExpired: "Oturumunuz sona erdi. Yeniden giriş yapın." },
  fa: { appName: "عملیات CROUS", signIn: "ورود", username: "نام کاربری تلگرام", password: "گذرواژه", signOut: "خروج", dashboard: "داشبورد", administrators: "مدیران", paidUsers: "کاربران پولی", transactions: "تراکنش‌ها", overview: "نمای کلی", week: "هفته", month: "ماه", year: "سال", totalUsers: "کاربران", paidSubscribers: "اشتراک‌های پولی فعال", monitoringAnchors: "جستجوهای فعال", revenue: "درآمد", recentBuyers: "خریداران اخیر", search: "جستجو", previous: "قبلی", next: "بعدی", page: "صفحه", of: "از", results: "نتیجه", loading: "در حال بارگیری", empty: "رکوردی نیست", retry: "تلاش دوباره", error: "بارگیری داده ممکن نشد.", addAdmin: "افزودن مدیر", name: "نام", role: "نقش", status: "وضعیت", created: "ایجاد", lastLogin: "آخرین ورود", active: "فعال", inactive: "غیرفعال", superadmin: "مدیر ارشد", admin: "مدیر", createAdmin: "ایجاد مدیر", passwordHelp: "حداقل ۱۲ نویسه با حرف بزرگ، کوچک و عدد.", showPassword: "نمایش گذرواژه", hidePassword: "پنهان کردن گذرواژه", cancel: "لغو", save: "ذخیره", close: "بستن", viewDetails: "جزئیات", plan: "طرح", starts: "شروع", ends: "پایان", lastPayment: "آخرین پرداخت", activeSearches: "جستجوهای فعال", transaction: "تراکنش", amount: "مبلغ", mode: "حالت", live: "زنده", test: "آزمایشی", purchased: "خرید", identifier: "شناسه", language: "زبان", searchArea: "محدودهٔ جستجو", keyboardHelp: "راهنمای صفحه‌کلید", keyboardBody: "Tab میان کنترل‌ها جابه‌جا می‌شود. Enter یا Space سطر را باز می‌کند. Escape پنجره را می‌بندد.", skip: "رفتن به محتوا", menu: "منو", filters: "فیلترها", noData: "برای این دوره داده‌ای نیست", refresh: "به‌روزرسانی", signedInAs: "واردشده به عنوان", invalidLogin: "نام کاربری و گذرواژه را بررسی کنید.", required: "این فیلد اجباری است.", unknown: "در دسترس نیست", monitoring: "پایش", current: "فعلی", sessionExpired: "نشست شما پایان یافت. دوباره وارد شوید." },
  ar: { appName: "عمليات CROUS", signIn: "تسجيل الدخول", username: "اسم مستخدم تيليجرام", password: "كلمة المرور", signOut: "تسجيل الخروج", dashboard: "لوحة التحكم", administrators: "المسؤولون", paidUsers: "المستخدمون المدفوعون", transactions: "المعاملات", overview: "نظرة عامة", week: "أسبوع", month: "شهر", year: "سنة", totalUsers: "المستخدمون", paidSubscribers: "اشتراكات مدفوعة نشطة", monitoringAnchors: "عمليات بحث نشطة", revenue: "الإيرادات", recentBuyers: "أحدث المشترين", search: "بحث", previous: "السابق", next: "التالي", page: "صفحة", of: "من", results: "نتائج", loading: "جارٍ التحميل", empty: "لا توجد سجلات", retry: "حاول مجددًا", error: "تعذر تحميل هذه البيانات.", addAdmin: "إضافة مسؤول", name: "الاسم", role: "الدور", status: "الحالة", created: "تاريخ الإنشاء", lastLogin: "آخر دخول", active: "نشط", inactive: "غير نشط", superadmin: "مسؤول أعلى", admin: "مسؤول", createAdmin: "إنشاء مسؤول", passwordHelp: "12 حرفًا على الأقل مع حرف كبير وصغير ورقم.", showPassword: "إظهار كلمة المرور", hidePassword: "إخفاء كلمة المرور", cancel: "إلغاء", save: "حفظ", close: "إغلاق", viewDetails: "عرض التفاصيل", plan: "الخطة", starts: "البداية", ends: "النهاية", lastPayment: "آخر دفعة", activeSearches: "عمليات بحث نشطة", transaction: "المعاملة", amount: "المبلغ", mode: "الوضع", live: "مباشر", test: "اختبار", purchased: "تاريخ الشراء", identifier: "المعرف", language: "اللغة", searchArea: "منطقة البحث", keyboardHelp: "مساعدة لوحة المفاتيح", keyboardBody: "ينقل Tab التركيز بين العناصر. يفتح Enter أو Space الصف. يغلق Escape النوافذ.", skip: "انتقل إلى المحتوى", menu: "القائمة", filters: "عوامل التصفية", noData: "لا توجد بيانات لهذه الفترة", refresh: "تحديث", signedInAs: "تم الدخول باسم", invalidLogin: "تحقق من اسم المستخدم وكلمة المرور.", required: "هذا الحقل مطلوب.", unknown: "غير متاح", monitoring: "المراقبة", current: "الحالي", sessionExpired: "انتهت جلستك. سجّل الدخول مجددًا." }
};

const preferenceMessages = {
  en: { appearance: "Appearance", automatic: "Auto", light: "Light", dark: "Dark" },
  fr: { appearance: "Apparence", automatic: "Auto", light: "Clair", dark: "Sombre" },
  ru: { appearance: "Оформление", automatic: "Авто", light: "Светлая", dark: "Тёмная" },
  uk: { appearance: "Вигляд", automatic: "Авто", light: "Світла", dark: "Темна" },
  tr: { appearance: "Görünüm", automatic: "Otomatik", light: "Açık", dark: "Koyu" },
  fa: { appearance: "ظاهر", automatic: "خودکار", light: "روشن", dark: "تیره" },
  ar: { appearance: "المظهر", automatic: "تلقائي", light: "فاتح", dark: "داكن" }
};

for (const [locale, copy] of Object.entries(preferenceMessages)) Object.assign(messages[locale], copy);

const referralOwnerMessages = {
  en: { referralDashboard: "Referral dashboard", referralLinkExpired: "This secure link is invalid or has expired. Open a new link from the referral bot." },
  fr: { referralDashboard: "Tableau de bord de parrainage", referralLinkExpired: "Ce lien sécurisé est invalide ou a expiré. Ouvrez un nouveau lien depuis le bot de parrainage." },
  ru: { referralDashboard: "Реферальная статистика", referralLinkExpired: "Эта защищённая ссылка недействительна или истекла. Откройте новую ссылку в реферальном боте." },
  uk: { referralDashboard: "Статистика рефералів", referralLinkExpired: "Це захищене посилання недійсне або прострочене. Відкрийте нове посилання в реферальному боті." },
  tr: { referralDashboard: "Yönlendirme istatistikleri", referralLinkExpired: "Bu güvenli bağlantı geçersiz veya süresi dolmuş. Yönlendirme botundan yeni bir bağlantı açın." },
  fa: { referralDashboard: "آمار ارجاع", referralLinkExpired: "این پیوند امن نامعتبر یا منقضی شده است. یک پیوند جدید را از ربات ارجاع باز کنید." },
  ar: { referralDashboard: "إحصاءات الإحالة", referralLinkExpired: "هذا الرابط الآمن غير صالح أو منتهي الصلاحية. افتح رابطًا جديدًا من بوت الإحالة." }
};

for (const [locale, copy] of Object.entries(referralOwnerMessages)) Object.assign(messages[locale], copy);

Object.assign(messages.en, {
  reports: "Reports", report: "Report", submitted: "Submitted", preview: "Preview",
  user: "User", platform: "Platform", fullReport: "Full report",
  referrals: "Referrals", createReferral: "Create referral", ownerUsername: "Owner Telegram username",
  referralCode: "Referral code", available: "Available", earned: "Lifetime earnings", paid: "Paid out",
  copyLink: "Copy link", referralLinkCopied: "Referral link copied.", copyFailed: "Could not copy the referral link.",
  attachedUsers: "Attached users", pendingWithdrawals: "Pending withdrawals", referralIncome: "Referral commission income",
  referralPurchases: "Referral purchases", customerPayment: "Customer payment", referralCommission: "Referral commission", currency: "Currency",
  delete: "Delete", deleteReferral: "Delete referral", deleteReferralConfirm: "This hides the referral from active use but keeps its history, commissions, and payouts."
});

export function resolveLocale(input) {
  const candidate = (input || "en").toLowerCase().split("-")[0];
  return localeCodes.includes(candidate) ? candidate : "en";
}
